/**
 * src/types/index.ts
 *
 * Domain types for the Waffles platform.
 * These mirror the database schema - keep them in sync with supabase/migrations/.
 *
 * Naming: DB row types live in database.ts (auto-generated by Supabase CLI).
 * These are the application-level types we use in components and business logic.
 */

// ─── User / Auth ──────────────────────────────────────────────────────────────

export type UserTier = "guest" | "basic" | "id_verified";

export type UserRole = "user" | "mod" | "principal";

export type StackTier =
  | "short_stack"   // 0 completed - new, no history
  | "fresh_stack"   // 1-9 completed
  | "rising_stack"  // 10-24 completed
  | "buttery_stack" // 25-99 completed
  | "golden_stack"; // 100+ completed

export type ChefTier =
  | "new_chef"        // 0-9 completed waffles
  | "trusted_chef"    // 10+ completed
  | "established_chef"// 25+ completed
  | "power_chef";     // 100+ completed

export interface WaffleUser {
  id: string;
  email: string;
  username: string;
  display_name: string | null;
  avatar_url: string | null;
  tier: UserTier;
  role: UserRole;
  stack_tier: StackTier;
  chef_tier: ChefTier;
  rep_score: number;          // 0.0 - 5.0 (half-waffle precision)
  completed_waffles_chef: number;
  completed_waffles_diner: number;
  is_banned: boolean;
  ban_expires_at: string | null;
  fingerprint_id: string | null;
  created_at: string;
}

// ─── Waffle (listing) ─────────────────────────────────────────────────────────

export type WaffleStatus =
  | "draft"           // being built, not visible
  | "pending_review"  // submitted, awaiting mod approval (>$1k or firearms)
  | "active"          // seats on sale
  | "filled"          // 100% seats sold, pending draw
  | "drawing"         // draw in progress
  | "drawn"           // winner selected, pending shipping
  | "shipped"         // tracking number added
  | "delivered"       // carrier confirms delivery
  | "verified"        // buyer clicked Verified
  | "completed"       // funds released, transaction closed
  | "voided"          // cancelled, all refunds issued
  | "disputed";       // active dispute

export type ItemCondition = "A+" | "A" | "B" | "C" | "D" | "F";

export type DrawStyle =
  | "spin"   // spinning wheel
  | "drop"   // plinko/ball drop
  | "slot"   // slot machine
  | "roll"   // dice (low seat count)
  | "cage"   // lottery ball cage
  | "deal";  // card draw

export type DrawType = "automated" | "live";

export type WinnerPrivacy = "full" | "partial" | "public";

export interface WaffleItem {
  id: string;
  title: string;
  description: string;
  condition: ItemCondition;
  is_new: boolean;
  declared_value: number;       // seller's stated value in USD
  ai_valuation: number | null;  // platform AI check result
  ai_valuation_flag: "none" | "soft_warning" | "hard_block";
  photos: string[];             // Supabase Storage URLs
  category: string;
  is_firearm: boolean;
  is_restricted: boolean;
}

export interface Waffle {
  id: string;
  chef_id: string;
  chef: WaffleUser;

  // Listing content
  title: string;
  description: string;
  items: WaffleItem[];          // array - single item or Stack (bundle)
  is_stack: boolean;

  // Seat structure
  seat_price: number;           // USD cents
  total_seats: number;
  seats_sold: number;
  allow_seat_choice: boolean;   // false = random assignment only

  // Status and lifecycle
  status: WaffleStatus;
  created_at: string;
  goes_live_at: string | null;
  deadline: string;             // max 30 days from going live
  filled_at: string | null;
  drawn_at: string | null;
  completed_at: string | null;

  // Draw config
  draw_style: DrawStyle;
  draw_type: DrawType;
  draw_scheduled_at: string | null;
  draw_audit_id: string | null; // RANDOM.ORG unique ID
  winner_id: string | null;
  winner_privacy: WinnerPrivacy;
  winner_seat_number: number | null;

  // Shipping
  shipping_carrier: "ups" | "fedex" | "usps" | "local_pickup" | null;
  tracking_number: string | null;
  label_url: string | null;
  shipped_at: string | null;
  delivered_at: string | null;

  // Moderation
  is_featured: boolean;
  flag_count: number;
  review_notes: string | null;
  approved_by: string | null;

  // Mini Waffle
  mini_waffle_id: string | null;

  // Totals (denormalized for performance)
  total_pot: number;            // seat_price * total_seats in USD cents
  platform_fee: number;         // 10% of pot
}

// ─── Seat ─────────────────────────────────────────────────────────────────────

export type SeatStatus =
  | "available"
  | "reserved"    // in someone's cart - NOT held, first-pay-first-served
  | "authorized"  // Stripe pre-auth captured
  | "captured"    // payment fully captured (100% fill triggered)
  | "refunded";   // waffle voided, pre-auth released

export interface Seat {
  id: string;
  waffle_id: string;
  seat_number: number;          // 1-based
  status: SeatStatus;
  holder_id: string | null;
  authorized_at: string | null;
  captured_at: string | null;
  stripe_payment_intent_id: string | null;
}

// ─── Draw ─────────────────────────────────────────────────────────────────────

export interface Draw {
  id: string;
  waffle_id: string;
  draw_type: DrawType;
  draw_style: DrawStyle;
  random_org_request_id: string;
  random_org_signature: string;
  winning_seat_number: number;
  winner_id: string;
  conducted_at: string;
  operator_id: string | null;   // for live draws only
  stream_url: string | null;    // for live draws only
  audit_log_url: string;        // public RANDOM.ORG verification link
}

// ─── Rep + Feedback ───────────────────────────────────────────────────────────

export type FeedbackRole = "chef" | "diner";

export interface Feedback {
  id: string;
  waffle_id: string;
  from_user_id: string;
  to_user_id: string;
  from_role: FeedbackRole;

  // Sub-scores (1.0-5.0 in 0.5 increments)
  score_overall: number;
  score_description: number | null;    // chef only
  score_shipping_speed: number | null; // chef only
  score_communication: number;
  score_verification_speed: number | null; // diner only
  score_dispute_behavior: number | null;   // diner only

  text: string;                        // 20 char minimum
  is_negative: boolean;
  is_neutral: boolean;

  submitted_at: string;
  revealed_at: string | null;          // blind - revealed when both submit or 30d expires
  window_closes_at: string;
}

// ─── Dispute ──────────────────────────────────────────────────────────────────

export type DisputeStatus =
  | "open"
  | "awaiting_chef_response"
  | "awaiting_diner_response"
  | "partial_refund_offered"
  | "escalated_to_host"
  | "resolved_chef_favor"
  | "resolved_diner_favor"
  | "closed";

export interface Dispute {
  id: string;
  waffle_id: string;
  opened_by: string;
  status: DisputeStatus;
  description: string;
  evidence_urls: string[];
  partial_refund_amount: number | null;  // USD cents
  host_id: string | null;
  host_decision: string | null;
  opened_at: string;
  resolved_at: string | null;
}

// ─── Mini Waffle ──────────────────────────────────────────────────────────────

export interface MiniWaffle {
  id: string;
  parent_waffle_id: string;
  seat_price: number;               // cheaper than parent
  total_seats: number;
  seats_sold: number;
  status: WaffleStatus;
  restricted_to_holders: boolean;   // existing ticket holders only?
  deadline: string;
  pulls: MiniWafflePull[];
}

export interface MiniWafflePull {
  pull_number: number;
  seats_awarded: number;            // how many main seats this pull wins
  main_seat_numbers: number[];      // which specific main seats
  winner_id: string | null;
}

// ─── Notifications ────────────────────────────────────────────────────────────

export type NotificationType =
  | "waffle_filled"
  | "draw_scheduled"
  | "draw_result_win"
  | "draw_result_loss"
  | "item_shipped"
  | "item_delivered"
  | "verify_reminder"
  | "feedback_reminder"
  | "feedback_revealed"
  | "dispute_opened"
  | "dispute_update"
  | "mod_action"
  | "rep_change";

export interface Notification {
  id: string;
  user_id: string;
  type: NotificationType;
  title: string;
  body: string;
  waffle_id: string | null;
  is_read: boolean;
  created_at: string;
}

// ─── Cart (client-side state only, not persisted) ────────────────────────────

export interface CartItem {
  waffle_id: string;
  waffle_title: string;
  seat_number: number;
  seat_price: number;           // USD cents
  chef_username: string;
}

export interface Cart {
  items: CartItem[];
  total: number;                // USD cents
}

// ─── API response wrappers ────────────────────────────────────────────────────

export interface ApiSuccess<T> {
  ok: true;
  data: T;
}

export interface ApiError {
  ok: false;
  error: string;
  code?: string;
}

export type ApiResponse<T> = ApiSuccess<T> | ApiError;
