/**
 * src/types/database.ts
 *
 * This file is auto-generated by the Supabase CLI.
 * DO NOT edit manually - run the following to regenerate after schema changes:
 *
 *   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts
 *
 * Until you run that command, this placeholder keeps TypeScript happy.
 */

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
